### PR TITLE
updated to last symfony security changes

### PR DESCRIPTION
**Pull request by lenar**
Thanks to @tecbot and @jmikola for the code

### CODE REVIEW

**Comment by stof** [comment]
Note: we need to create a branch before merging it.

And it would be better to add the composer.json file before tagging a release.

**Comment by arghav** [comment]
Created the tag 1.0.0

**Comment by arghav** [comment]
Ah... missed adding composer.json. Removed the tag, will add composer and create the tag.

**Comment by stof** [comment]
removing a tag is not a clean solution at all. Every people that fetched the repo with the old tag will still have the old tag until he deletes the tag locally and fetches again.

**Comment by arghav** [comment]
@stof I deleted it quickly so I hope no one took it in that time. Anyway will keep that in mind.

**Comment by arghav** [comment]
@stof Good to create the 1.0.0 tag? Should we create a branch too?

**Comment by stof** [comment]
yes, we need a branch too to allow bug fixes for the Symfony 2.0 version. I will take a look at the bundle to see its state

**Comment by stof** [comment]
@kertz I pinged you on other opened pull requests. Please review them before tagging the release

**Comment by arghav** [comment]
@stof I will be tagging the 1.0.0 release, is it fine?

**Comment by stof** [comment]
@kertz yes. Also create a branch for bug fixes for 1.0 as the master branch will then be incompatible with symfony 2.0 (and add a note in the readme to avoid people to complain about the incompatibility)

**Pull request merged**
