### PR TITLE
added acces_token parameters

### PR DESCRIPTION
**Pull request by carlossg00**
added needed options to have access_token & access_token_secret keys in the configuration file.
That way TwitterOAuth is created with access keys and no call to setOAuthToken(access_token,access_token_secret) method is needed in the simplest use case of the rest api.

See http://blog.azancadas.com/2011/09/fostwitterbundle-simple-way-to-tweet/ for a use case.

### CODE REVIEW

**Comment by lsmith77** [comment]
@schmittjoh: ping

**Comment by stof** [comment]
@kertz @schmittjoh ping

**Comment by arghav** [comment]
`access_token` and `access_token_secret` are unique to each authenticated Twitter accounts. So IMHO it would not make sense to put it in the config. They should be stored in the database for each authenticated user and made available as a session parameter.

**Comment by bamarni** [comment]
@kertz: Could you please reconsider this?

The TwitterOAuth class is designed to accept an OAuth token and secret in its constructor's signature, so why the bundle should not be compliant with that?

This feature makes sense when you only use the api to connect to your website's twitter account (to get the last tweets for example), in this case you have a static token and secret, and the most simple way to proceed would be as suggested in this PR.

**Comment by schmittjoh** [comment]
Yeah, in the latter scenario it does indeed make sense if you are solely using this bundle as a means to access the Twitter API with your own account.

Did you test this patch, and does it still work against master?

**Comment by bamarni** [comment]
Yep I've just tested it against master and it's working, looks fine for me!

**Comment by schmittjoh** [comment]
Assuming that @kertz has no objections, I have merged this PR now.

**Comment by arghav** [comment]
@schmittjoh No problem

**Pull request merged**
